CREATE TABLE g5_linhas_terminal(
   id_terminal     INTEGER  NOT NULL
  ,linhas_terminal VARCHAR(64) NOT NULL
  ,PRIMARY KEY(id_terminal,linhas_terminal)
);
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'256 - Barreirinha / Guadalupe');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'505 - Boqueirao / Centro Civico');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'507 - Sitio Cercado (via Boqueirao)');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'508 - Sitio Cercado (via Pinheirinho)');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'702 - Caiua / Cachoeira');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'A06 - Tamandare / Guadalupe (via Minerios)');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'B01 - Maracana / Guadalupe (via Santa Candida)');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'B03 - Guaraituba / Guadalupe (via Alto da XV/Maracana)');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'B69 - Madrugueiro Curitiba / Sao Dimas');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'B73 - Curitiba / Jardim Osasco');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'B76 - Curitiba / Sao Sebastiao');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'B77 - Curitiba / Jardim Curitiba');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'B78 - Curitiba / Jardim Sao Gabriel');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'B89 - Guarairuba / Guadalupe - via Cabral / Maracana');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'S01 - Roca Grande / Guadalupe');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'S61 - Curitiba / Santa Fe');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'C03 - Pinhais / Guadalupe');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'C64 - Madrugueiro Curitiba / Pinhais');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'C66 - Curitiba / Vila Zumbi');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'C72 - Curitiba / Vila Palmital (via Conjunto Atuba)');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'E01 - Curitiba / Urano');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'E03 - Curitiba / Afonso Pena (via BR-277)');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'E67 - Curitiba / Braga (via Ouro Fino)');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'E68 - Curitiba / Quississana');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'E71 - Curitiba / Jardim Ipe');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'E72 - Curitiba / Jardim Izaura');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'E73 - Curitiba / Jardim Cruzeiro');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'E76 - Curitiba / Posto Paris');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'E77 - Curitiba / Guatupe');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'E78 - Curitiba / Roseira');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'E79 - Curitiba / Jardim Izaura (via Jardim Ipe)');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'E99 - Sao Jose / Guadalupe (via Terminal Central)');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'F71 - Fazenda / Guadalupe');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'H01 - Araucaria / Guadalupe');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'N62 - Jardim Paulista / Guadalupe');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'N63 - Eugenia Maria / Guadalupe');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'N73 - Jardim Paulista / Guadalupe (via Quatro Barras)');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'O69 - Madrugueiro Curitiba / Quatro Barras');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'O74 - Quatro Barras / Guadalupe');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10166,'K01 - Itaperucu / Guadalupe (via Minerios/Tamandare)');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (7,'030 - Interbairros III');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (7,'307 - Bairro Alto / Santa Felicidade');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (7,'229 - Madrugueiro Penha / Fernando de Noronha');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (7,'389 - Madrugueiro Taruma / Augusta');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (8,'A15 - Cachoeira / Cabral');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (8,'A18 - Tamandare / Cabral');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (8,'A31 - Jardim Graziela');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (8,'A32 - Vila Prado');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (9,'200 - Ligeirao Santa Candida / Pc. do Japao');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (9,'203 - Santa Candida / Capao Raso');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (9,'222 - Vila Esperanca');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (9,'224 - Cassiopeia');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (9,'225 - Boa Vista / Barreirinha');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (9,'226 - Abaete');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (9,'342 - Bairro Alto / Boa Vista');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (9,'B43 - Rio Verde');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (9,'209 - Madrugueiro Santa Candida / Capao Raso');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (9,'229 - Madrugueiro Penha / Fernando de Noronha');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10,'E07 - Sao Jose / Boqueirao - Linha Direta');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10,'509 - Madrugueiro Boqueirao');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10,'E11 - Boqueirao / Afonso Pena');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10,'E21 - Boqueirao / Centro Sao Jose');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10,'E32 - Aeroporto / Boqueirao - Linha Direta via Terminal Sao Jose');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10,'519 - Madrugueiro Sao Francisco / Iguape');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10,'549 - Madrugueiro Bairro Novo');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (11,'201 - Cabral / Bom Retiro');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (11,'207 - Cabral / Osorio');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (11,'211 - Colina Verde');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (11,'212 - Solar');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (11,'213 - Sao Joao');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (11,'214 - Tingui');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (11,'216 - Cabral / Portao');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (11,'245 - Anita Garibaldi');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (11,'A04 - Tamandare / Cabral');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (11,'A15 - Cachoeira / Cabral');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (11,'A18 - Tamandare / Cabral');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (11,'B02 - Maracana / Cabral');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (11,'B05 - Guaraituba / Cabral');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (11,'209 - Madrugueiro Santa Candida / Capao Raso');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (11,'B07 - Guaraituba / Cabral - via Maracana');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (11,'B20 - Guaraituba / Cabral - via Maracana');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (11,'B89 - Guaraituba / Guadalupe - via Maracana / Cabral');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (12,'060 - Interbairros VI');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (12,'702 - Caiua / Cachoeira');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (13,'303 - Centenario / Campo Comprido');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (14,'303 - Centenario / Campo Comprido');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (15,'311 - Araguaia');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (15,'C01 - Pinhais / Rui Barbosa');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (15,'Z03 - Vicente de Carvalho / Capao da Imbuia');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (15,'308 - Madrugueiro Centenario / Rui Barbosa');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (15,'309 - Madrugueiro Centenario');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (16,'620 - Santa Cruz');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (16,'621 - Fanny');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (16,'622 - Rondon');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (16,'623 - Parque Industrial');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (16,'624 - Vila Sao Pedro');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (16,'625 - Gramados');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (16,'627 - Bosh');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (16,'628 - Carbomafra');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (16,'629 - Alto Boqueirao');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (16,'654 - Campo Alegre');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (16,'657 - Xaxim / Capao Raso');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (16,'658 - Capao Raso / Caiua');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (16,'828 - Campo Comprido / Capao Raso');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (16,'831 - Fazendinha / Capao Raso');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (16,'H02 - Araucaria / Capao Raso');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (16,'H20 - Angelica / Capao Raso');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (16,'209 - Madrugueiro Santa Candida / Capao Raso');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (16,'609 - Madrugueiro CIC');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (17,'500 - Ligeirao Boqueirao');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (17,'502 - Circular Sul - sentido horario');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (17,'503 - Boqueirao');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (17,'602 - Circular Sul - sentido anti-horario');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (17,'030 - Interbairros III');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (17,'505 - Boqueirao / Centro Civico');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (17,'507 - Sitio Cercado - sentido horario');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (17,'508 - Sitio Cercado - sentido anti-horario');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (17,'521 - Nivaldo Braga');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (17,'522 - Maringa');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (17,'523 - Iguape I');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (17,'509 - Madrugueiro Boqueirao');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (18,'302 - Centenario / Rui Barbosa');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (18,'303 - Centenario / Campo Comprido');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (18,'305 - Centenario');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (18,'322 - Camargo');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (18,'331 - Mercurio');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (18,'332 - Acropole');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (18,'334 - Agricola');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (18,'335 - Centenario / Boqueirao');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (18,'336 - Vila Reno');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (18,'338 - Centenario / Hauer');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (18,'C36 - Pinhais Centenario');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (18,'308 - Madrugueiro Centenario / Rui Barbosa');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (18,'309 - Madrugueiro Centenario');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (19,'040 - Interbairros IV');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (20,'701 - Fazendinha');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (20,'706 - Fazendinha - Caiua / Centro');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (20,'789 - Madrugueira Caiua');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (20,'778 - Cotolengo');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (21,'338 - Centenario / Hauer');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (21,'511 - Sao Francisco');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (21,'512 - Itamarati');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (21,'513 - Hauer / Boqueirao');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (21,'515 - Iguape II');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (21,'516 - Canal Belem / Salgado Filho');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (21,'621 - Fanny');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (21,'X14 - Reforco Hauer');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (21,'519 - Sao Francisco / Iguape');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (21,'509 - Madrugueiro Boqueirao');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (22,'308 - Madrugueiro Centenario / Rui Barbosa');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (22,'309 - Madrugueiro Centenario');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'600 - Kamyr / Quartel General');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'630 - Vitoria Regia');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'631 - Piratini / BR-476');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'632 - Quartel General');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'633 - Maria Angelica');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'635 - Londrina');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'636 - Rio Negro');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'637 - Santa Joana');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'638 - Pinheirinho');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'639 - Futurama');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'640 - Palmeira');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'641 - Luiz Nichele');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'642 - Ganchinho');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'643 - Umbara');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'644 - Pinheirinho / CIC');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'646 - Pompeia - Janaina');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'649 - Pirineus');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'650 - Santa Rita / Pinheirinho');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'655 - Jardim da Ordem');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'656 - Kamyr');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'659 - Cachimba - Olaria');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'680 - Rurbana');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'681 - Dalagassa');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'684 - Rio Bonito');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'688 - Pinheirinho / Zoologico');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'690 - Vila Juliana');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'772 - Tupy / Juliana');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'F01 - Fazenda / Pinheirinho');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'F03 - Fazenda Direto');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'H11 - Araucaria / Pinheirinho');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'H24 - Angelica / Pinheirinho - direto');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'609 - Madrugueiro CIC');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'679 - Madrugueiro');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (23,'G11 - Quitandinha / Pinheirinho');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (24,'209 - Madrugueiro Santa Candida / Capao Raso-');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (24,'609 - Madrugueiro CIC');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'200 - Ligeirao Santa Candida / P. do Japao');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'203 - Santa Candida / Capao Raso');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'030 - Interbairros III');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'214 - Tingui');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'231 - Banestado / California');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'232 - Alianca');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'233 - Olaria');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'236 - Sao Benedito');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'237 - Parque Atuba');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'341 - Bairro Alto / Santa Candida');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'924 - Santa Felicidade / Santa Candida');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'B11 - Maracana / Santa Candida');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'B39 - Campo Alto / Santa Candida');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'B57 - Campo Alto / Santa Candida -circular');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'B58 - Maracana / Santa Candida - circular');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'S01 - Roca Grande / Guadalupe');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'S31 - Roca Grande / Santa Candida');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'S32 - Roca Grande / Santa Candida - Direto');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'O31 - Santa Candida / Caron - via Quatro Barras');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (26,'209 - Madrugueiro Santa Candida / Capao Raso');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (27,'040 - Interbairros IV');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (27,'P11 - Campo Magro');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (27,'P12 - Campo Magro - via Sao Benedito');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (27,'P13 - Bom Pastor');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (27,'P14 - Jardim Boa Vista');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (27,'P15 - Jardim Pioneiro');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (27,'P16 - Jardim Boa Vista - via Padre Aleixo');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (27,'P17 - Campo Novo / Santa Felicidade');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (27,'P59 - Bom Pastor - via Jardim Pioneiro');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'502 - Circular Sul - sentido horario');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'602 - Circulat Sul - sentido anti-horario');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'X11 - Capao Raso / Sitio Cercado');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'X12 - Especial Boqueirao');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'X20 - Portao / Sitio Cercado');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'506 - Bairro Novo');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'507 - Sitio Cercado - sentido horario');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'508 - Sitio Cercado - sentido anti-horario');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'527 - Pinheirinho / Boqueirao');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'610 - Capao Raso / Sitio Cercado');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'524 - Bairro Novo B / C');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'534 - Parigot de Souza');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'540 - Boqueirao / Mondelez');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'541 - Bairro Novo A');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'542 - Bairro Novo B');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'545 - Trabalhador');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'547 - Bairro Novo C');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'548 - Osternak / Sitio Cercado');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'552 - Sambaqu');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'625 - Gramados');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'637 - Santa Joana');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'649 - Pirineus');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'683 - Futurama / Sitio Cercado');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'688 - Pinheirinho / Zoologico');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (25,'549 - Madrugueiro Bairro Novo');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10495,'617 - Jd. Ludovica');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10495,'650 - Santa Rita / Pinheirinho');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10495,'680 - Rurbana');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10495,'681 - Dalagassa');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10495,'684 - Rio Bonito / Pinheirinho');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10495,'685 - Rio Bonito / CIC');
INSERT INTO g5_linhas_terminal(id_terminal,linhas_terminal) VALUES (10495,'773 - Vizinhanca Santa Rita');