CREATE TABLE G5_LINHAS_ONIBUS(
   id_ponto        INTEGER  NOT NULL
  ,linha_de_onibus VARCHAR(117) NOT NULL
  ,PRIMARY KEY(id_ponto,linha_de_onibus)
 ,FOREIGN KEY(id_ponto) REFERENCES g5_ponto_de_onibus_canaleta(id_ponto)
);
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13402,'050 - Interbairros V, sentido Terminal Oficinas');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13401,'050 - Interbairros V, sentido Terminal Portao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11298,'200 - Lifgeirao Santa Candida/Pc. do Japao, sentido Estacao Tubo Bento Viana (nao opera aos domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11311,'200 - Ligeirao Santa Candida / Pc. do Japao (apenas dersembarque)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11300,'200 - Ligeirao Santa Candida / Pc. do Japao, sentido Estacao Tubo Bento Viana');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11299,'200 - Ligeirao Santa Candida / Pc. do Japao, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11310,'200 - Ligeirao Santa Candida / Pc. do Japao, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11301,'200 - Ligeirao Santa Candida/Pc. do Japao, sentido Estacao Tubo Bento Viana (nao opera aos domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11307,'200 - Ligeirao Santa Candida/Pc. do Japao, sentido Estacao Tubo Bento Viana (nao opera aos domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11297,'200 - Ligeirao Santa Candida/Pc. do Japao, sentido Terminal Santa Candida (nao opera aos domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11302,'200 - Ligeirao Santa Candida/Pc. do Japao, sentido Terminal Santa Candida (nao opera aos domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11306,'200 - Ligeirao Santa Candida/Pc. do Japao, sentido Terminal Santa Candida (nao opera aos domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11319,'202 - Cabra/Capao Raso, sentido Terminal Capao Raso (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11331,'202 - Cabral / Capao Raso sentido Terminal Cabral');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11289,'202 - Cabral / Capao Raso, sentido Terminal Cabral');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11293,'202 - Cabral / Capao Raso, sentido Terminal Cabral');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11299,'202 - Cabral / Capao Raso, sentido Terminal Cabral');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11303,'202 - Cabral / Capao Raso, sentido Terminal Cabral');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11308,'202 - Cabral / Capao Raso, sentido Terminal Cabral');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11310,'202 - Cabral / Capao Raso, sentido Terminal Cabral');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11316,'202 - Cabral / Capao Raso, sentido Terminal Cabral');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11324,'202 - Cabral / Capao Raso, sentido Terminal Cabral');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11326,'202 - Cabral / Capao Raso, sentido Terminal Cabral');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11328,'202 - Cabral / Capao Raso, sentido Terminal Cabral');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11320,'202 - Cabral / Capao Raso, sentido Terminal Cabral (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11290,'202 - Cabral / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11294,'202 - Cabral / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11300,'202 - Cabral / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11304,'202 - Cabral / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11309,'202 - Cabral / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11311,'202 - Cabral / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11317,'202 - Cabral / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11325,'202 - Cabral / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11327,'202 - Cabral / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11329,'202 - Cabral / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11330,'202 - Cabral / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11321,'202 - Cabral / Capao Raso, sentido Terminal Capao Raso (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11291,'202 - Cabral/Capao Raso, sentido Terminal Cabral (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11295,'202 - Cabral/Capao Raso, sentido Terminal Cabral (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11297,'202 - Cabral/Capao Raso, sentido Terminal Cabral (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11302,'202 - Cabral/Capao Raso, sentido Terminal Cabral (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11306,'202 - Cabral/Capao Raso, sentido Terminal Cabral (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11312,'202 - Cabral/Capao Raso, sentido Terminal Cabral (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11314,'202 - Cabral/Capao Raso, sentido Terminal Cabral (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11318,'202 - Cabral/Capao Raso, sentido Terminal Cabral (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11322,'202 - Cabral/Capao Raso, sentido Terminal Cabral (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11292,'202 - Cabral/Capao Raso, sentido Terminal Capao Raso (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11296,'202 - Cabral/Capao Raso, sentido Terminal Capao Raso (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11298,'202 - Cabral/Capao Raso, sentido Terminal Capao Raso (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11301,'202 - Cabral/Capao Raso, sentido Terminal Capao Raso (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11307,'202 - Cabral/Capao Raso, sentido Terminal Capao Raso (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11313,'202 - Cabral/Capao Raso, sentido Terminal Capao Raso (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11315,'202 - Cabral/Capao Raso, sentido Terminal Capao Raso (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11323,'202 - Cabral/Capao Raso, sentido Terminal Capao Raso (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11331,'203 - Santa Candida / Capao Raso sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11280,'203 - Santa Candida / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11282,'203 - Santa Candida / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11284,'203 - Santa Candida / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11286,'203 - Santa Candida / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11290,'203 - Santa Candida / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11294,'203 - Santa Candida / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11300,'203 - Santa Candida / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11304,'203 - Santa Candida / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11309,'203 - Santa Candida / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11311,'203 - Santa Candida / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11317,'203 - Santa Candida / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11321,'203 - Santa Candida / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11325,'203 - Santa Candida / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11327,'203 - Santa Candida / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11329,'203 - Santa Candida / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11330,'203 - Santa Candida / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11279,'203 - Santa Candida / Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11281,'203 - Santa Candida / Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11283,'203 - Santa Candida / Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11285,'203 - Santa Candida / Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11287,'203 - Santa Candida / Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11289,'203 - Santa Candida / Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11293,'203 - Santa Candida / Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11299,'203 - Santa Candida / Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11303,'203 - Santa Candida / Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11308,'203 - Santa Candida / Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11310,'203 - Santa Candida / Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11316,'203 - Santa Candida / Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11320,'203 - Santa Candida / Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11324,'203 - Santa Candida / Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11326,'203 - Santa Candida / Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11328,'203 - Santa Candida / Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11301,'203 - Santa Candida/Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11307,'203 - Santa Candida/Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11313,'203 - Santa Candida/Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11315,'203 - Santa Candida/Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11319,'203 - Santa Candida/Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11323,'203 - Santa Candida/Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11278,'203 - Santa Candida/Capao Raso, sentido Terminal Capao Raso.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11292,'203 - Santa Candida/Capao Raso, sentido Terminal Capao Raso.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11296,'203 - Santa Candida/Capao Raso, sentido Terminal Capao Raso.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11298,'203 - Santa Candida/Capao Raso, sentido Terminal Capao Raso.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11302,'203 - Santa Candida/Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11306,'203 - Santa Candida/Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11312,'203 - Santa Candida/Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11314,'203 - Santa Candida/Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11318,'203 - Santa Candida/Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11322,'203 - Santa Candida/Capao Raso, sentido Terminal Santa Candida');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11277,'203 - Santa Candida/Capao Raso, sentido Terminal Santa Candida.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11291,'203 - Santa Candida/Capao Raso, sentido Terminal Santa Candida.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11295,'203 - Santa Candida/Capao Raso, sentido Terminal Santa Candida.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11297,'203 - Santa Candida/Capao Raso, sentido Terminal Santa Candida.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11288,'203 - Santa Canduda / Capao Raso, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13398,'211 - Colina Verde, sentido Colina Verde');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13397,'211 - Colina Verde, sentido Terminal Cabral');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11415,'302 - Centenario / Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11417,'302 - Centenario / Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11421,'302 - Centenario / Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11423,'302 - Centenario / Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11427,'302 - Centenario / Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11431,'302 - Centenario / Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11433,'302 - Centenario / Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11429,'302 - Centenario / Rui Barbosa, sentido Pc. Rui Barbosa (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11435,'302 - Centenario / Rui Barbosa, sentido Pc. Rui Barbosa (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11414,'302 - Centenario / Rui Barbosa, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11416,'302 - Centenario / Rui Barbosa, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11420,'302 - Centenario / Rui Barbosa, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11422,'302 - Centenario / Rui Barbosa, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11426,'302 - Centenario / Rui Barbosa, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11430,'302 - Centenario / Rui Barbosa, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11432,'302 - Centenario / Rui Barbosa, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11428,'302 - Centenario / Rui Barbosa, sentido Terminal Centenario (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11434,'302 - Centenario / Rui Barbosa, sentido Terminal Centenario (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11443,'302 - Centenario/Rui Barbosa, exclusivo para desembarque (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11438,'302 - Centenario/Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11301,'302 - Centenario/Rui Barbosa, sentido Pc. Rui Barbosa (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11419,'302 - Centenario/Rui Barbosa, sentido Pc. Rui Barbosa (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11425,'302 - Centenario/Rui Barbosa, sentido Pc. Rui Barbosa (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11437,'302 - Centenario/Rui Barbosa, sentido Pc. Rui Barbosa (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11439,'302 - Centenario/Rui Barbosa, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11302,'302 - Centenario/Rui Barbosa, sentido Terminal Centenario (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11418,'302 - Centenario/Rui Barbosa, sentido Terminal Centenario (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11424,'302 - Centenario/Rui Barbosa, sentido Terminal Centenario (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11436,'302 - Centenario/Rui Barbosa, sentido Terminal Centenario (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11442,'302 - Centenario/Rui Barbosa, sentido Terminal Centenario (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11415,'303 - Centenario / Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11417,'303 - Centenario / Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11421,'303 - Centenario / Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11423,'303 - Centenario / Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11427,'303 - Centenario / Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11429,'303 - Centenario / Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11431,'303 - Centenario / Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11433,'303 - Centenario / Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11435,'303 - Centenario / Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11449,'303 - Centenario / Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11455,'303 - Centenario / Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11457,'303 - Centenario / Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11458,'303 - Centenario / Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11459,'303 - Centenario / Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11471,'303 - Centenario / Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11446,'303 - Centenario / Campo Comprido, sentido Terminal Campo Comprido.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11473,'303 - Centenario / Campo Comprido, sentido Terminal Campo Comprido.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11414,'303 - Centenario / Campo Comprido, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11416,'303 - Centenario / Campo Comprido, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11420,'303 - Centenario / Campo Comprido, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11422,'303 - Centenario / Campo Comprido, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11426,'303 - Centenario / Campo Comprido, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11428,'303 - Centenario / Campo Comprido, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11430,'303 - Centenario / Campo Comprido, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11432,'303 - Centenario / Campo Comprido, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11434,'303 - Centenario / Campo Comprido, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11448,'303 - Centenario / Campo Comprido, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11454,'303 - Centenario / Campo Comprido, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11470,'303 - Centenario / Campo Comprido, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11447,'303 - Centenario / Campo Comprido, sentido Terminal Centenario.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11472,'303 - Centenario / Campo Comprido, sentido Terminal Centenario.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11301,'303 - Centenario/Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11425,'303 - Centenario/Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11437,'303 - Centenario/Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11438,'303 - Centenario/Campo comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11453,'303 - Centenario/Campo Comprido, sentido Terminal Campo Comprido');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11305,'303 - Centenario/Campo Comprido, sentido Terminal Campo Comprido.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11419,'303 - Centenario/Campo Comprido, sentido Terminal Campo Comprido.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11444,'303 - Centenario/Campo comprido, sentido Terminal Campo Comprido.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11451,'303 - Centenario/Campo Comprido, sentido Terminal Campo Comprido.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11461,'303 - Centenario/Campo Comprido, sentido Terminal Campo Comprido.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11463,'303 - Centenario/Campo Comprido, sentido Terminal Campo Comprido.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11465,'303 - Centenario/Campo Comprido, sentido Terminal Campo Comprido.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11467,'303 - Centenario/Campo Comprido, sentido Terminal Campo Comprido.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11469,'303 - Centenario/Campo Comprido, sentido Terminal Campo Comprido.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11302,'303 - Centenario/Campo Comprido, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11424,'303 - Centenario/Campo Comprido, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11436,'303 - Centenario/Campo Comprido, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11439,'303 - Centenario/Campo Comprido, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11456,'303 - Centenario/Campo Comprido, sentido Terminal Centenario');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11418,'303 - Centenario/Campo Comprido, sentido Terminal Centenario.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11440,'303 - Centenario/Campo Comprido, sentido Terminal Centenario.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11445,'303 - Centenario/Campo Comprido, sentido Terminal Centenario.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11450,'303 - Centenario/Campo Comprido, sentido Terminal Centenario.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11452,'303 - Centenario/Campo Comprido, sentido Terminal Centenario.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11460,'303 - Centenario/Campo Comprido, sentido Terminal Centenario.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11462,'303 - Centenario/Campo Comprido, sentido Terminal Centenario.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11464,'303 - Centenario/Campo Comprido, sentido Terminal Centenario.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11466,'303 - Centenario/Campo Comprido, sentido Terminal Centenario.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11468,'303 - Centenario/Campo Comprido, sentido Terminal Centenario.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13398,'350 - Ligeirao Fagundes Varela / Pinheirinho, apenas desembarque');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13400,'350 - Ligeirao Fagundes Varela / Pinheirinho, sentido Estacao Fagundes Varela.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11474,'350 - Ligeirao Fagundes Varela / Pinheirinho, sentido Fagundes Varela');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11476,'350 - Ligeirao Fagundes Varela / Pinheirinho, sentido Fagundes Varela');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11478,'350 - Ligeirao Fagundes Varela / Pinheirinho, sentido Fagundes Varela');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11480,'350 - Ligeirao Fagundes Varela / Pinheirinho, sentido Fagundes Varela');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11482,'350 - Ligeirao Fagundes Varela / Pinheirinho, sentido Fagundes Varela');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13402,'350 - Ligeirao Fagundes Varela / Pinheirinho, sentido Fagundes Varela');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11475,'350 - Ligeirao Fagundes Varela / Pinheirinho, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11477,'350 - Ligeirao Fagundes Varela / Pinheirinho, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11479,'350 - Ligeirao Fagundes Varela / Pinheirinho, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11481,'350 - Ligeirao Fagundes Varela / Pinheirinho, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13397,'350 - Ligeirao Fagundes Varela / Pinheirinho, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13401,'350 - Ligeirao Fagundes Varela / Pinheirinho, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13399,'350 - Ligeirao Fagundes Varela / Pinheirinho, sentido Terminal Pinheirinho.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11483,'350 Ligeirao Fagundes Varela / Pinheirinho, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13397,'374 - Hugo Lange, sentido Pc. Santos Andrade');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13398,'374 - Hugo Lange, sentido Terminal Bairro Alto');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13401,'471 - Vila Sao Paulo, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13402,'471 - Vila Sao Paulo, sentido Vila Sao Paulo');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13401,'472 - Uberaba, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13402,'472 - Uberaba, sentido Uberaba');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13402,'475 - Canal Belem, sentido Canal Belem');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13401,'475 - Canal Belem, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13401,'477 - Vila Macedo (via Guabirotuba), sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13402,'477 - Vila Macedo (via Guabirotuba), sentido Vila Macedo');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11341,'500 - Ligeirao Boqueirao, exclusivo para desembarque (nao opera aos domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11343,'500 - Ligeirao Boqueirao, exclusivo para desembarque (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11359,'500 - Ligeirao Boqueirao, sentido Pc. Carlos Gomes');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11358,'500 - Ligeirao Boqueirao, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11340,'500 - Ligeirao Boqueirao, sentido Terminal Boqueirao (nao opera aos domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11342,'500 - Ligeirao Boqueirao, sentido Terminal Boqueirao (nao opera aos domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11331,'502 - Circular Sul sentido Terminal Carmo');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11369,'502 - Circular Sul, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11393,'502 - Circular Sul, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11482,'502 - Circular Sul, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11389,'502 - Circular Sul, sentido Terminal Boqueirao.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11391,'502 - Circular Sul, sentido Terminal Boqueirao.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11333,'502 - Circular Sul, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11337,'502 - Circular Sul, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11339,'502 - Circular Sul, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11372,'502 - Circular Sul, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11374,'502 - Circular Sul, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11376,'502 - Circular Sul, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11378,'502 - Circular Sul, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11382,'502 - Circular Sul, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11384,'502 - Circular Sul, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11326,'502 - Circular Sul, sentido Terminal Carmo');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11328,'502 - Circular Sul, sentido Terminal Carmo');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11363,'502 - Circular Sul, sentido Terminal Carmo');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11335,'502 - Circular Sul, sentido Terminal Hauer');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11358,'502 - Circular Sul, sentido Terminal Hauer');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11361,'502 - Circular Sul, sentido Terminal Hauer');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11397,'502 - Circular Sul, sentido Terminal Hauer.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11371,'502 - Circular Sul, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11401,'502 - Circular Sul, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11403,'502 - Circular Sul, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11407,'502 - Circular Sul, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11399,'502 - Circular Sul, sentido Terminal Portao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11405,'502 - Circular Sul, sentido Terminal Portao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11365,'502 - Circular Sul, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11367,'502 - Circular Sul, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11380,'502 - Circular Sul, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11386,'502 - Circular Sul, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11395,'502 - CircularSul, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11341,'503 - Boqueirao, exclusivo para desembarque.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11343,'503 - Boqueirao, exclusivo para desembarque.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11344,'503 - Boqueirao, sentido Pc. Carlos Gomes');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11346,'503 - Boqueirao, sentido Pc. Carlos Gomes');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11349,'503 - Boqueirao, sentido Pc. Carlos Gomes');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11355,'503 - Boqueirao, sentido Pc. Carlos Gomes');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11357,'503 - Boqueirao, sentido Pc. Carlos Gomes');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11359,'503 - Boqueirao, sentido Pc. Carlos Gomes');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11360,'503 - Boqueirao, sentido Pc. Carlos Gomes');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11362,'503 - Boqueirao, sentido Pc. Carlos Gomes');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11364,'503 - Boqueirao, sentido Pc. Carlos Gomes');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11366,'503 - Boqueirao, sentido Pc. Carlos Gomes');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11368,'503 - Boqueirao, sentido Pc. Carlos Gomes');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11370,'503 - Boqueirao, sentido Pc. Carlos Gomes');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11350,'503 - Boqueirao, sentido Pc. Carlos Gomes.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11353,'503 - Boqueirao, sentido Pc. Carlos Gomes.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11345,'503 - Boqueirao, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11347,'503 - Boqueirao, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11348,'503 - Boqueirao, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11352,'503 - Boqueirao, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11354,'503 - Boqueirao, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11356,'503 - Boqueirao, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11358,'503 - Boqueirao, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11365,'503 - Boqueirao, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11367,'503 - Boqueirao, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11371,'503 - Boqueirao, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11340,'503 - Boqueirao, sentido Terminal Boqueirao.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11342,'503 - Boqueirao, sentido Terminal Boqueirao.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11351,'503 - Boqueirao, sentido Terminal Boqueirao.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11361,'503 - Boqueirao, sentido Terminal Boqueirao.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11363,'503 - Boqueirao, sentido Terminal Boqueirao.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11369,'503 - Boqueirao, sentido Terminal Boqueirao.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11485,'550 - Ligeirao Pinheirinho / Carlos Gomes, exclusivo para desembarque.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11346,'550 - Ligeirao Pinheirinho / Carlos Gomes, sentido Pc. Carlos Gomes');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11476,'550 - Ligeirao Pinheirinho / Carlos Gomes, sentido Pc. Carlos Gomes');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11480,'550 - Ligeirao Pinheirinho / Carlos Gomes, sentido Pc. Carlos Gomes');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11347,'550 - Ligeirao Pinheirinho / Carlos Gomes, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11477,'550 - Ligeirao Pinheirinho / Carlos Gomes, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11481,'550 - Ligeirao Pinheirinho / Carlos Gomes, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11484,'550 - Ligeirao Pinheirinho / Carlos Gomes, sentido Terminal Pinheirinho.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11487,'550 - Ligeirao Pinheirinho/Carlos Gomes, exclusivo para desembarque.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11474,'550 - Ligeirao Pinheirinho/Carlos Gomes, sentido Pc. Carlos Gomes');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11482,'550 - Ligeirao Pinheirinho/Carlos Gomes, sentido Pc. Carlos Gomes');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11355,'550 - Ligeirao Pinheirinho/Carlos Gomes, sentido Pc. Carlos Gomes.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11478,'550 - Ligeirao Pinheirinho/Carlos Gomes, sentido Pc. Carlos Gomes.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11475,'550 - Ligeirao Pinheirinho/Carlos Gomes, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11479,'550 - Ligeirao Pinheirinho/Carlos Gomes, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11483,'550 - Ligeirao Pinheirinho/Carlos Gomes, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11354,'550 - Ligeirao Pinheirinho/Carlos Gomes, sentido Terminal Pinheirinho.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11486,'550 - Ligeirao Pinheirinho/Carlos Gomes, sentido Terminal Pinheirinho.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11334,'602 - Circular Sul, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11381,'602 - Circular Sul, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11387,'602 - Circular Sul, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11364,'602 - Circular Sul, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11366,'602 - Circular Sul, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11398,'602 - Circular Sul, sentido Terminal Carmo');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11404,'602 - Circular Sul, sentido Terminal Carmo');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11368,'602 - Circular Sul, sentido Terminal Carmo.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11373,'602 - Circular Sul, sentido Terminal Hauer');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11375,'602 - Circular Sul, sentido Terminal Hauer');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11377,'602 - Circular Sul, sentido Terminal Hauer');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11379,'602 - Circular Sul, sentido Terminal Hauer');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11383,'602 - Circular Sul, sentido Terminal Hauer');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11385,'602 - Circular Sul, sentido Terminal Hauer');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11362,'602 - Circular Sul, sentido Terminal Hauer.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11332,'602 - Circular Sul, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11336,'602 - Circular Sul, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11338,'602 - Circular Sul, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11392,'602 - Circular Sul, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11394,'602 - Circular Sul, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11483,'602 - Circular Sul, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11388,'602 - Circular Sul, sentido Terminal Pinheirinho.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11390,'602 - Circular Sul, sentido Terminal Pinheirinho.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11359,'602 - Circular Sul, sentido Terminal Portao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11370,'602 - Circular Sul, sentido Terminal Portao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11360,'602 - Circular Sul, sentido Terminal Portao.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11396,'602 - Circular Sul, sentido Terminal Portao.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11327,'602 - Circular Sul, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11329,'602 - Circular Sul, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11330,'602 - Circular Sul, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11400,'602 - Circular Sul, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11402,'602 - Circular Sul, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11406,'602 - Circular Sul, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11331,'603 - Pinheirinho / Rui Barbosa sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11308,'603 - Pinheirinho / Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11310,'603 - Pinheirinho / Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11316,'603 - Pinheirinho / Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11324,'603 - Pinheirinho / Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11326,'603 - Pinheirinho / Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11328,'603 - Pinheirinho / Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11320,'603 - Pinheirinho / Rui Barbosa, sentido Pc. Rui Barbosa.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11309,'603 - Pinheirinho / Rui Barbosa, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11311,'603 - Pinheirinho / Rui Barbosa, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11317,'603 - Pinheirinho / Rui Barbosa, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11325,'603 - Pinheirinho / Rui Barbosa, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11327,'603 - Pinheirinho / Rui Barbosa, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11329,'603 - Pinheirinho / Rui Barbosa, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11330,'603 - Pinheirinho / Rui Barbosa, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11321,'603 - Pinheirinho / Rui Barbosa, sentido Terminal Pinheirinho.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11492,'603 - Pinheirinho/Rui Barbosa, exclusivo para desembarque.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11333,'603 - Pinheirinho/Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11335,'603 - Pinheirinho/Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11337,'603 - Pinheirinho/Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11339,'603 - Pinheirinho/Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11306,'603 - Pinheirinho/Rui Barbosa, sentido Pc. Rui Barbosa.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11312,'603 - Pinheirinho/Rui Barbosa, sentido Pc. Rui Barbosa.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11318,'603 - Pinheirinho/Rui Barbosa, sentido Pc. Rui Barbosa.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11322,'603 - Pinheirinho/Rui Barbosa, sentido Pc. Rui Barbosa.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11332,'603 - Pinheirinho/Rui Barbosa, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11334,'603 - Pinheirinho/Rui Barbosa, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11336,'603 - Pinheirinho/Rui Barbosa, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11338,'603 - Pinheirinho/Rui Barbosa, sentido Terminal Pinheirinho');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11307,'603 - Pinheirinho/Rui Barbosa, sentido Terminal Pinheirinho.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11313,'603 - Pinheirinho/Rui Barbosa, sentido Terminal Pinheirinho.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11315,'603 - Pinheirinho/Rui Barbosa, sentido Terminal Pinheirinho.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11319,'603 - Pinheirinho/Rui Barbosa, sentido Terminal Pinheirinho.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11323,'603 - Pinheirinho/Rui Barbosa, sentido Terminal Pinheirinho.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11441,'603 - Pinheirinho/Rui Barbosa, sentido Terminal Pinheirinho.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11314,'603 - Pinheirinho/Rui Brbosa, sentido Pc. Rui Barbosa.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11481,'616 - Portao / Santa Bernadethe - Linha Verde, sentido Terminal Portao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11479,'616 - Portao/Santa Bernadethe-Linha Verde, sentido Terminal Portao.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11480,'621 - Fanny, sentido Terminal Capao Raso.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11481,'621 - Fanny, sentido Terminal Hauer.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11474,'624 - Vila Sao Pedro, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11475,'624 - Vila Sao Pedro, sentido Xaxim');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11474,'625 - Gramados, sentido Terminal Capao Raso.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11475,'625 - Gramados, sentido Terminal Sitio Cercado.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11477,'629 - Alto Boqueirao, sentido Alto Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11476,'629 - Alto Boqueirao, sentido Terminal Capao Raso');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11476,'657 - Xaxim / Capao Raso, sentido Terminal Capao Raso.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11477,'657 - Xaxim / Capao Raso, sentido Xaxim.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13397,'B42 - Maracana / Linha Verde, sentido Estacao PUC.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13398,'B42 - Maracana / Linha Verde, sentido Terminal Maracana');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13402,'B42 - Maracana / Linha Verde, sentido Terminal Maracana');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11408,'C01 - Pinhais / Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11427,'C01 - Pinhais / Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11431,'C01 - Pinhais / Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11433,'C01 - Pinhais / Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11429,'C01 - Pinhais / Rui Barbosa, sentido Pc. Rui Barbosa.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11435,'C01 - Pinhais / Rui Barbosa, sentido Pc. Rui Barbosa.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11409,'C01 - Pinhais / Rui Barbosa, sentido Terminal Pinhais');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11426,'C01 - Pinhais / Rui Barbosa, sentido Terminal Pinhais');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11430,'C01 - Pinhais / Rui Barbosa, sentido Terminal Pinhais');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11432,'C01 - Pinhais / Rui Barbosa, sentido Terminal Pinhais');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11428,'C01 - Pinhais / Rui Barbosa, sentido Terminal Pinhais.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11434,'C01 - Pinhais / Rui Barbosa, sentido Terminal Pinhais.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11443,'C01 - Pinhais/Rui Barbosa, exclusivo para desembarque.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11411,'C01 - Pinhais/Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11412,'C01 - Pinhais/Rui Barbosa, sentido Pc. Rui Barbosa');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11301,'C01 - Pinhais/Rui Barbosa, sentido Pc. Rui Barbosa.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11425,'C01 - Pinhais/Rui Barbosa, sentido Pc. Rui Barbosa.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11437,'C01 - Pinhais/Rui Barbosa, sentido Pc. Rui Barbosa.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11438,'C01 - Pinhais/Rui Barbosa, sentido Pc. Rui Barbosa.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11410,'C01 - Pinhais/Rui Barbosa, sentido Terminal Pinhais');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11413,'C01 - Pinhais/Rui Barbosa, sentido Terminal Pinhais');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11302,'C01 - Pinhais/Rui Barbosa, sentido Terminal Pinhais.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11424,'C01 - Pinhais/Rui Barbosa, sentido Terminal Pinhais.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11436,'C01 - Pinhais/Rui Barbosa, sentido Terminal Pinhais.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11439,'C01 - Pinhais/Rui Barbosa, sentido Terminal Pinhais.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11442,'C01 - Pinhais/Rui Barbosa, sentido Terminal Pinhais.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11408,'C04 - Capao da Imbuia / Pinhais, sentido Terminal Capao da Imbuia (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11409,'C04 - Capao da Imbuia / Pinhais, sentido Terminal Pinhais (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11411,'C04 - Capao da Imbuia/Pinhais, sentido Terminal Capao da Imbuia (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11412,'C04 - Capao da Imbuia/Pinhais, sentido Terminal Capao da Imbuia (nao opera aos sabados, domingos e feriados)');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11410,'C04 - Capao da Imbuia/Pinhais, sentido Terminal Pinhais (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11413,'C04 - Capao da Imbuia/Pinhais, sentido Terminal Pinhais (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13401,'F01 - Curitiba / Fazenda Rio Grande, sentido Pc. Carlos Gomes.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13402,'F01 - Curitiba / Fazenda Rio Grande, sentido Terminal Fazenda Rio Grande.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11482,'F02 - Curitiba/Fazenda Rio Grande, sentido Pc. Carlos Gomes.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11483,'F02 - Curitiba/Fazenda Rio Grande, sentido Terminal Fazenda Rio Grande.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (13398,'N01 - Jardim Paulista / Fagundes Varela.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11399,'X11 - Sitio Cercado / Capao Raso, sentido Terminal Capao Raso (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11405,'X11 - Sitio Cercado / Capao Raso, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11333,'X11 - Sitio Cercado/Capao Raso, sentido Terminal Capao Raso (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11337,'X11 - Sitio Cercado/Capao Raso, sentido Terminal Capao Raso (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11339,'X11 - Sitio Cercado/Capao Raso, sentido Terminal Capao Raso (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11401,'X11 - Sitio Cercado/Capao Raso, sentido Terminal Capao Raso (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11403,'X11 - Sitio Cercado/Capao Raso, sentido Terminal Capao Raso (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11407,'X11 - Sitio Cercado/Capao Raso, sentido Terminal Capao Raso (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11335,'X11 - Sitio Cercado/Capao Raso, sentido Terminal Capao Raso.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11373,'X12 - Especial Boqueirao, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11375,'X12 - Especial Boqueirao, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11377,'X12 - Especial Boqueirao, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11379,'X12 - Especial Boqueirao, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11383,'X12 - Especial Boqueirao, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11385,'X12 - Especial Boqueirao, sentido Terminal Boqueirao');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11381,'X12 - Especial Boqueirao, sentido Terminal Boqueirao (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11387,'X12 - Especial Boqueirao, sentido Terminal Boqueirao (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11372,'X12 - Especial Boqueirao, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11374,'X12 - Especial Boqueirao, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11376,'X12 - Especial Boqueirao, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11378,'X12 - Especial Boqueirao, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11382,'X12 - Especial Boqueirao, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11384,'X12 - Especial Boqueirao, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11380,'X12 - Especial Boqueirao, sentido Terminal Sitio Cercado (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11386,'X12 - Especial Boqueirao, sentido Terminal Sitio Cercado (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11327,'X20 - Portao / Sitio Cercado, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11329,'X20 - Portao / Sitio Cercado, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11330,'X20 - Portao / Sitio Cercado, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11404,'X20 - Portao / Sitio Cercado, sentido Terminal Sitio Cercado');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11398,'X20 - Portao / Sitio Cercado, sentido Terminal Sitio Cercado (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11336,'X20 - Portao/Sitio Cercado, sentido Terminal Sitio Cercado (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11338,'X20 - Portao/Sitio Cercado, sentido Terminal Sitio Cercado (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11400,'X20 - Portao/Sitio Cercado, sentido Terminal Sitio Cercado (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11402,'X20 - Portao/Sitio Cercado, sentido Terminal Sitio Cercado (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11406,'X20 - Portao/Sitio Cercado, sentido Terminal Sitio Cercado (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11334,'X20 - Portao/Sitio Cercado, sentido Terminal Sitio Cercado.');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11332,'X20 - Portao/Sitio Cercdo, sentido Terminal Sitio Cercado (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11408,'X30 - Reforco Capao da Imbuia, sentido Terminal Capao da Imbuia (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11411,'X30 - Reforco Capao da Imbuia, sentido Terminal Capao da Imbuia (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11412,'X30 - Reforco Capao da Imbuia, sentido Terminal Capao da Imbuia (nao opera aos sabados, domingos e feriados).');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11455,'X31 - Reforco Campina do Siqueira, sentido Terminal Campina do Siqueira');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11457,'X31 - Reforco Campina do Siqueira, sentido Terminal Campina do Siqueira');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11459,'X31 - Reforco Campina do Siqueira, sentido Terminal Campina do Siqueira');
INSERT INTO G5_LINHAS_ONIBUS(id_ponto,linha_de_onibus) VALUES (11453,'X31 - Reforco Campina do Siqueira, sentido Terminal Campina do Siqueira (nao opera aos sabados, domingos e feriados).');
