CREATE TABLE g5_ponto_de_onibus_canaleta(
   id_ponto   INTEGER  NOT NULL
  ,nome_ponto VARCHAR(34) NOT NULL
  ,rua        VARCHAR(30) NOT NULL
  ,numero     INTEGER  NOT NULL
  ,bairro     VARCHAR(15) NOT NULL
  ,regional   VARCHAR(16) NOT NULL
  ,id_bairro  INTEGER  NOT NULL
  ,PRIMARY KEY(id_ponto)
  ,FOREIGN KEY(id_bairro) REFERENCES g5_bairro_cidade(id_bairro)
);


INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11304,'ALFERES POLI 1','AV. SETE DE SETEMBRO',3356,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11303,'ALFERES POLI 2','AV. SETE DE SETEMBRO',3211,'REBOUCAS','MATRIZ',54);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11346,'ALMIRANTE GONCALVES 1','AV. MAL. FLORIANO PEIXOTO',2039,'REBOUCAS','MATRIZ',54);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11347,'ALMIRANTE GONCALVES 2','AV. MAL. FLORIANO PEIXOTO',2170,'REBOUCAS','MATRIZ',54);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11393,'ANTERO DE QUENTAL 1','AV. PRES. WENCESLAU BRAZ',1985,'LINDOIA','PINHEIRINHO',44);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11392,'ANTERO DE QUENTAL 2','AV. PRES. WENCESLAU BRAZ',1984,'GUAIRA','PORTAO',36);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11288,'ANTONIO CAVALHEIRO 1','AV. PARANA',961,'CABRAL','MATRIZ',18);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11287,'ANTONIO CAVALHEIRO 2','AV. PARANA',1250,'CABRAL','MATRIZ',18);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11371,'ANTONIO DE PAULA 1','AV. MAL. FLORIANO PEIXOTO',9856,'BOQUEIRAO','BOQUEIRAO',16);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11370,'ANTONIO DE PAULA 2','AV. MAL. FLORIANO PEIXOTO',9715,'BOQUEIRAO','BOQUEIRAO',16);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11282,'ANTONIO LAGO 1','AV. PARANA',3179,'BOA VISTA','BOA VISTA',14);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11281,'ANTONIO LAGO 2','AV. PARANA',3220,'BACACHERI','BOA VISTA',9);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11421,'ANTONIO MEIRELLES SOBRINHO 1','R. ENG. COSTA BARROS',63,'CAJURU','CAJURU',20);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11420,'ANTONIO MEIRELLES SOBRINHO 2','R. ENG. COSTA BARROS',64,'CAJURU','CAJURU',20);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11382,'ARACA 1','R. WILSON DACHEUX PEREIRA',1235,'ALTO BOQUEIRAO','BOQUEIRAO',4);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11383,'ARACA 2','R. WILSON DACHEUX PEREIRA',1098,'ALTO BOQUEIRAO','BOQUEIRAO',4);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11405,'ARROIO CERCADO 1','R. RICARDO GASPARIAN MACHADO',1759,'SITIO CERCADO','BAIRRO NOVO',66);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11404,'ARROIO CERCADO 2','R. RICARDO GASPARIAN MACHADO',1760,'SITIO CERCADO','BAIRRO NOVO',66);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11311,'BENTO VIANA 1','AV. SETE DE SETEMBRO',4906,'BATEL','MATRIZ',12);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11310,'BENTO VIANA 2','AV. SETE DE SETEMBRO',4905,'AGUA VERDE','PORTAO',2);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11456,'BIGORRILHO 1','R. PE. ANCHIETA',2151,'BIGORRILHO','MATRIZ',13);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11457,'BIGORRILHO 2','R. PE. ANCHIETA',2150,'BIGORRILHO','MATRIZ',13);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11290,'BOM JESUS 1','AV. PARANA',31,'CABRAL','MATRIZ',18);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11289,'BOM JESUS 2','AV. PARANA',80,'CABRAL','MATRIZ',18);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11448,'BRIGADEIRO FRANCO 1','R. PROF. FERNANDO MOREIRA',675,'MERCES','MATRIZ',45);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11449,'BRIGADEIRO FRANCO 2','R. PROF. FERNANDO MOREIRA',604,'MERCES','MATRIZ',45);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11454,'BRUNO FILGUEIRA 1','R. PE. ANCHIETA',1775,'BIGORRILHO','MATRIZ',13);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11455,'BRUNO FILGUEIRA 2','R. PE. ANCHIETA',1776,'BIGORRILHO','MATRIZ',13);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11417,'CAJURU 1','R. ENG. COSTA BARROS',1649,'CAJURU','CAJURU',20);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11416,'CAJURU 2','R. ENG. COSTA BARROS',1650,'CAJURU','CAJURU',20);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11324,'CARLOS DIETSCH 1','AV. REPUBLICA ARGENTINA',3039,'PORTAO','PORTAO',52);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11325,'CARLOS DIETSCH 2','AV. REPUBLICA ARGENTINA',3090,'PORTAO','PORTAO',52);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11415,'CATULO DA PAIXAO CEARENSE 1','R. FILIPINAS',183,'CAJURU','CAJURU',20);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11414,'CATULO DA PAIXAO CEARENSE 2','R. FILIPINAS',228,'CAJURU','CAJURU',20);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11299,'CENTRAL 1','R. PRES. FARIA',50,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11300,'CENTRAL 2','R. PRES. FARIA',49,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11349,'CONSELHEIRO DANTAS 1','AV. MAL. FLORIANO PEIXOTO',2610,'PRADO VELHO','MATRIZ',53);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11348,'CONSELHEIRO DANTAS 2','AV. MAL. FLORIANO PEIXOTO',2509,'PAROLIN','PORTAO',49);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11294,'CONSTANTINO MAROCHI 1','AV. JOAO GUALBERTO',1287,'ALTO DA GLORIA','MATRIZ',5);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11293,'CONSTANTINO MAROCHI 2','AV. JOAO GUALBERTO',1416,'JUVEVE','MATRIZ',42);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11372,'COQUEIROS 1','R. IZAAC FERREIRA DA CRUZ',4295,'SITIO CERCADO','BAIRRO NOVO',66);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11373,'COQUEIROS 2','R. DOS PIONEIROS',1750,'SITIO CERCADO','BAIRRO NOVO',66);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11308,'CORONEL DULCIDIO 1','AV. SETE DE SETEMBRO',4341,'AGUA VERDE','PORTAO',2);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11309,'CORONEL DULCIDIO 2','AV. SETE DE SETEMBRO',4476,'BATEL','MATRIZ',12);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11366,'CORONEL LUIZ JOSE DOS SANTOS 1','AV. MAL. FLORIANO PEIXOTO',7797,'BOQUEIRAO','BOQUEIRAO',16);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11367,'CORONEL LUIZ JOSE DOS SANTOS 2','AV. MAL. FLORIANO PEIXOTO',7932,'BOQUEIRAO','BOQUEIRAO',16);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11427,'DELEGADO AMAZOR PRESTES 1','AV. PRES. AFFONSO CAMARGO',3209,'CAPAO DA IMBUIA','CAJURU',24);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11426,'DELEGADO AMAZOR PRESTES 2','AV. PRES. AFFONSO CAMARGO',3210,'CAJURU','CAJURU',20);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11395,'DOM ATICO 1','AV. PRES. WENCESLAU BRAZ',2615,'LINDOIA','PINHEIRINHO',44);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11394,'DOM ATICO 2','AV. PRES. WENCESLAU BRAZ',2614,'GUAIRA','PORTAO',36);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11316,'DOM PEDRO I 1','AV. REPUBLICA ARGENTINA',1015,'AGUA VERDE','PORTAO',2);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11317,'DOM PEDRO I 2','AV. REPUBLICA ARGENTINA',1160,'VILA IZABEL','PORTAO',73);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11374,'ERICO VERISSIMO 1','R. DOS PIONEIROS',2537,'ALTO BOQUEIRAO','BOQUEIRAO',4);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11375,'ERICO VERISSIMO 2','R. DOS PIONEIROS',2310,'ALTO BOQUEIRAO','BOQUEIRAO',4);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11384,'ERTON COELHO 1','R. WILSON DACHEUX PEREIRA',1797,'ALTO BOQUEIRAO','BOQUEIRAO',4);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11385,'ERTON COELHO 2','R. WILSON DACHEUX PEREIRA',1798,'ALTO BOQUEIRAO','BOQUEIRAO',4);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11378,'EUCALIPTOS 1','R. WILSON DACHEUX PEREIRA',183,'ALTO BOQUEIRAO','BOQUEIRAO',4);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11379,'EUCALIPTOS 2','R. WILSON DACHEUX PEREIRA',160,'ALTO BOQUEIRAO','BOQUEIRAO',4);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11376,'EUCLIDES DA CUNHA 1','R. DOS PIONEIROS',3101,'ALTO BOQUEIRAO','BOQUEIRAO',4);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11377,'EUCLIDES DA CUNHA 2','R. DOS PIONEIROS',3102,'ALTO BOQUEIRAO','BOQUEIRAO',4);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (13397,'FAGUNDES VARELA 1','ROD. BR-476',4470,'BACACHERI','BOA VISTA',9);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (13398,'FAGUNDES VARELA 2','ROD. BR-476',4470,'BAIRRO ALTO','BOA VISTA',10);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11480,'FANNY 1','ROD. BR-476',13097,'HAUER','BOQUEIRAO',37);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11481,'FANNY 2','ROD. BR-476',13080,'FANNY','PINHEIRINHO',32);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11280,'FERNANDO DE NORONHA 1','AV. PARANA',3693,'BOA VISTA','BOA VISTA',14);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11279,'FERNANDO DE NORONHA 2','AV. PARANA',3800,'TINGUI','BOA VISTA',70);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11357,'FERROVILA 1','AV. MAL. FLORIANO PEIXOTO',4501,'PRADO VELHO','MATRIZ',53);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11356,'FERROVILA 2','AV. MAL. FLORIANO PEIXOTO',4420,'PAROLIN','PORTAO',49);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11284,'GAGO COUTINHO 1','AV. PARANA',1997,'BOA VISTA','BOA VISTA',14);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11283,'GAGO COUTINHO 2','AV. PARANA',2150,'BACACHERI','BOA VISTA',9);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11459,'GASTAO CAMARA 1','R. PE. ANCHIETA',2618,'BIGORRILHO','MATRIZ',13);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11458,'GASTAO CAMARA 2','R. PE. ANCHIETA',2601,'BIGORRILHO','MATRIZ',13);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11423,'GERMANIA 1','AV. PREF. MAURICIO FRUET',2450,'CAJURU','CAJURU',20);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11422,'GERMANIA 2','AV. PREF. MAURICIO FRUET',2449,'CAJURU','CAJURU',20);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11344,'GETULIO VARGAS 1','AV. MAL. FLORIANO PEIXOTO',1571,'REBOUCAS','MATRIZ',54);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11345,'GETULIO VARGAS 2','AV. MAL. FLORIANO PEIXOTO',1702,'REBOUCAS','MATRIZ',54);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11331,'HERCULANO DE ARAUJO 1','AV. REPUBLICA ARGENTINA',4795,'NOVO MUNDO','PINHEIRINHO',47);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11330,'HERCULANO DE ARAUJO 2','AV. REPUBLICA ARGENTINA',4762,'NOVO MUNDO','PINHEIRINHO',47);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11364,'HIPOLITO DA COSTA 1','AV. MAL. FLORIANO PEIXOTO',7131,'BOQUEIRAO','BOQUEIRAO',16);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11365,'HIPOLITO DA COSTA 2','AV. MAL. FLORIANO PEIXOTO',7254,'BOQUEIRAO','BOQUEIRAO',16);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11286,'HOLANDA 1','AV. PARANA',1561,'BOA VISTA','BOA VISTA',14);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11285,'HOLANDA 2','AV. PARANA',1692,'BACACHERI','BOA VISTA',9);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11433,'HOSPITAL CAJURU 1','AV. PRES. AFFONSO CAMARGO',1681,'CRISTO REI','MATRIZ',31);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11432,'HOSPITAL CAJURU 2','AV. PRES. AFFONSO CAMARGO',1682,'JARDIM BOTANICO','MATRIZ',39);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11328,'HOSPITAL DO TRABALHADOR 1','AV. REPUBLICA ARGENTINA',4383,'NOVO MUNDO','PINHEIRINHO',47);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11329,'HOSPITAL DO TRABALHADOR 2','AV. REPUBLICA ARGENTINA',4540,'NOVO MUNDO','PINHEIRINHO',47);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11470,'IMPERIAL 1','R. DEP. HEITOR ALENCAR FURTADO',3133,'CAMPO COMPRIDO','SANTA FELICIDADE',22);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11471,'IMPERIAL 2','R. DEP. HEITOR ALENCAR FURTADO',3180,'CAMPO COMPRIDO','SANTA FELICIDADE',22);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11326,'ITAJUBA 1','AV. REPUBLICA ARGENTINA',4079,'NOVO MUNDO','PINHEIRINHO',47);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11327,'ITAJUBA 2','AV. REPUBLICA ARGENTINA',4074,'NOVO MUNDO','PINHEIRINHO',47);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11431,'JARDIM BOTANICO 1','AV. PRES. AFFONSO CAMARGO',2179,'CRISTO REI','MATRIZ',31);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11430,'JARDIM BOTANICO 2','AV. PRES. AFFONSO CAMARGO',2180,'JARDIM BOTANICO','MATRIZ',39);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11350,'JOAO VIANA SEILER 1','AV. MAL. FLORIANO PEIXOTO',2915,'PRADO VELHO','MATRIZ',53);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11351,'JOAO VIANA SEILER 2','AV. MAL. FLORIANO PEIXOTO',3006,'PAROLIN','PORTAO',49);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11278,'JOAQUIM NABUCO 1','AV. PARANA',4259,'SANTA CANDIDA','BOA VISTA',56);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11277,'JOAQUIM NABUCO 2','AV. PARANA',4420,'TINGUI','BOA VISTA',70);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11335,'JOSE CLEMENTINO BETTEGA 1','AV. WINSTON CHURCHILL',389,'CAPAO RASO','PINHEIRINHO',25);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11334,'JOSE CLEMENTINO BETTEGA 2','AV. WINSTON CHURCHILL',510,'CAPAO RASO','PINHEIRINHO',25);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11391,'LINDOIA 1','AV. PRES. WENCESLAU BRAZ',1555,'LINDOIA','PINHEIRINHO',44);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11390,'LINDOIA 2','AV. PRES. WENCESLAU BRAZ',1570,'GUAIRA','PORTAO',36);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11460,'MAJOR HEITOR GUIMARAES 1','R. DEP. HEITOR ALENCAR FURTADO',605,'MOSSUNGUE','SANTA FELICIDADE',46);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11461,'MAJOR HEITOR GUIMARAES 2','R. DEP. HEITOR ALENCAR FURTADO',600,'MOSSUNGUE','SANTA FELICIDADE',46);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11482,'MARECHAL FLORIANO 1','ROD. BR-476',12371,'HAUER','BOQUEIRAO',37);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11483,'MARECHAL FLORIANO 2','ROD. BR-476',12340,'PAROLIN','PORTAO',49);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11296,'MARIA CLARA 1','AV. JOAO GUALBERTO',741,'ALTO DA GLORIA','MATRIZ',5);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11295,'MARIA CLARA 2','AV. JOAO GUALBERTO',916,'ALTO DA GLORIA','MATRIZ',5);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11438,'MARIANO TORRES 1','AV. PRES. AFFONSO CAMARGO',5,'REBOUCAS','MATRIZ',54);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11439,'MARIANO TORRES 2','AV. PRES. AFFONSO CAMARGO',10,'REBOUCAS','MATRIZ',54);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11389,'MARUMBY 1','AV. PRES. WENCESLAU BRAZ',1155,'LINDOIA','PINHEIRINHO',44);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11388,'MARUMBY 2','AV. PRES. WENCESLAU BRAZ',1046,'GUAIRA','PORTAO',36);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11322,'MORRETES 1','AV. REPUBLICA ARGENTINA',2295,'PORTAO','PORTAO',52);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11323,'MORRETES 2','AV. REPUBLICA ARGENTINA',2478,'PORTAO','PORTAO',52);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11468,'MOSSUNGUE 1','R. DEP. HEITOR ALENCAR FURTADO',2721,'MOSSUNGUE','SANTA FELICIDADE',46);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11469,'MOSSUNGUE 2','R. DEP. HEITOR ALENCAR FURTADO',2720,'MOSSUNGUE','SANTA FELICIDADE',46);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11292,'MOYSES MARCONDES 1','AV. JOAO GUALBERTO',1697,'JUVEVE','MATRIZ',42);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11291,'MOYSES MARCONDES 2','AV. JOAO GUALBERTO',1836,'JUVEVE','MATRIZ',42);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11380,'NOVA EUROPA 1','R. WILSON DACHEUX PEREIRA',745,'ALTO BOQUEIRAO','BOQUEIRAO',4);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11381,'NOVA EUROPA 2','R. WILSON DACHEUX PEREIRA',720,'ALTO BOQUEIRAO','BOQUEIRAO',4);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11306,'OSWALDO CRUZ 1','AV. SETE DE SETEMBRO',3815,'REBOUCAS','MATRIZ',54);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11307,'OSWALDO CRUZ 2','AV. SETE DE SETEMBRO',3958,'BATEL','MATRIZ',12);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11339,'OURO VERDE 1','AV. WINSTON CHURCHILL',1285,'CAPAO RASO','PINHEIRINHO',25);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11338,'OURO VERDE 2','AV. WINSTON CHURCHILL',1400,'CAPAO RASO','PINHEIRINHO',25);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11360,'PADUA FLEURY 1','AV. MAL. FLORIANO PEIXOTO',5445,'HAUER','BOQUEIRAO',37);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11361,'PADUA FLEURY 2','AV. MAL. FLORIANO PEIXOTO',5560,'HAUER','BOQUEIRAO',37);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11355,'PAROLIN 1','AV. MAL. FLORIANO PEIXOTO',3919,'PRADO VELHO','MATRIZ',53);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11354,'PAROLIN 2','AV. MAL. FLORIANO PEIXOTO',3890,'PAROLIN','PORTAO',49);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11387,'PARQUE IGUACU 1','AV. MAL. FLORIANO PEIXOTO',10729,'BOQUEIRAO','BOQUEIRAO',16);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11386,'PARQUE IGUACU 2','AV. MAL. FLORIANO PEIXOTO',10828,'ALTO BOQUEIRAO','BOQUEIRAO',4);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11362,'PASSARELA 1','AV. MAL. FLORIANO PEIXOTO',6673,'BOQUEIRAO','BOQUEIRAO',16);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11363,'PASSARELA 2','AV. MAL. FLORIANO PEIXOTO',6794,'BOQUEIRAO','BOQUEIRAO',16);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11298,'PASSEIO PUBLICO 1','AV. JOAO GUALBERTO',179,'CENTRO CIVICO','MATRIZ',29);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11297,'PASSEIO PUBLICO 2','AV. JOAO GUALBERTO',180,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11412,'PASTOR MANOEL VIRGILIO DE SOUZA 1','AV. PRES. AFFONSO CAMARGO',5095,'CAPAO DA IMBUIA','CAJURU',24);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11413,'PASTOR MANOEL VIRGILIO DE SOUZA 2','AV. PRES. AFFONSO CAMARGO',5096,'CAJURU','CAJURU',20);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11464,'PAULO GORSKI 1','R. DEP. HEITOR ALENCAR FURTADO',1733,'MOSSUNGUE','SANTA FELICIDADE',46);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11465,'PAULO GORSKI 2','R. DEP. HEITOR ALENCAR FURTADO',1720,'MOSSUNGUE','SANTA FELICIDADE',46);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11411,'PAULO KISSULA 1','AV. PRES. AFFONSO CAMARGO',5611,'CAPAO DA IMBUIA','CAJURU',24);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11410,'PAULO KISSULA 2','AV. PRES. AFFONSO CAMARGO',5612,'CAJURU','CAJURU',20);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11333,'PEDRO GUSSO 1','AV. REPUBLICA ARGENTINA',5603,'CAPAO RASO','PINHEIRINHO',25);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11332,'PEDRO GUSSO 2','AV. REPUBLICA ARGENTINA',5602,'CAPAO RASO','PINHEIRINHO',25);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11314,'PETIT CARNEIRO 1','AV. REPUBLICA ARGENTINA',665,'AGUA VERDE','PORTAO',2);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11315,'PETIT CARNEIRO 2','AV. REPUBLICA ARGENTINA',760,'AGUA VERDE','PORTAO',2);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11340,'PRACA CARLOS GOMES 1','R. PEDRO IVO',355,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11341,'PRACA CARLOS GOMES 2','R. PEDRO IVO',385,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11486,'PRACA CARLOS GOMES 3','R. LOURENCO PINTO',69,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11487,'PRACA CARLOS GOMES 4','R. LOURENCO PINTO',83,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11452,'PRACA DA UCRANIA 1','R. PE. ANCHIETA',1359,'BIGORRILHO','MATRIZ',13);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11453,'PRACA DA UCRANIA 2','R. PE. ANCHIETA',1350,'BIGORRILHO','MATRIZ',13);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11302,'PRACA EUFRASIO CORREIA 1','AV. SETE DE SETEMBRO',2775,'REBOUCAS','MATRIZ',54);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11301,'PRACA EUFRASIO CORREIA 2','AV. SETE DE SETEMBRO',2848,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11445,'PRACA OSORIO 1','R. VISC. DE NACAR',1270,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11444,'PRACA OSORIO 2','R. VISC. DE NACAR',1271,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11441,'PRACA RUI BARBOSA 1','PC. RUI BARBOSA',790,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11492,'PRACA RUI BARBOSA 2','PC. RUI BARBOSA',790,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11442,'PRACA RUI BARBOSA 3','PC. RUI BARBOSA',790,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11443,'PRACA RUI BARBOSA 4','PC. RUI BARBOSA',790,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11440,'PRACA RUI BARBOSA 5','PC. RUI BARBOSA',741,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11305,'PRACA RUI BARBOSA 6','PC. RUI BARBOSA',765,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11450,'PRESIDENTE TAUNAY 1','R. PROF. FERNANDO MOREIRA',1041,'MERCES','MATRIZ',45);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11451,'PRESIDENTE TAUNAY 2','R. PROF. FERNANDO MOREIRA',996,'MERCES','MATRIZ',45);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11425,'PROFESSORA MARIA AGUIAR TEIXEIRA 1','AV. PRES. AFFONSO CAMARGO',3765,'CAPAO DA IMBUIA','CAJURU',24);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11424,'PROFESSORA MARIA AGUIAR TEIXEIRA 2','AV. PRES. AFFONSO CAMARGO',3766,'CAJURU','CAJURU',20);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (13401,'PUC 1','ROD. BR-476',11020,'PRADO VELHO','MATRIZ',53);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (13402,'PUC 2','ROD. BR-476',11020,'GUABIROTUBA','CAJURU',35);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11368,'QUARTEL 1','AV. MAL. FLORIANO PEIXOTO',9137,'BOQUEIRAO','BOQUEIRAO',16);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11369,'QUARTEL 2','AV. MAL. FLORIANO PEIXOTO',9280,'BOQUEIRAO','BOQUEIRAO',16);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11407,'QUITANDINHA 1','R. DOS PIONEIROS',489,'SITIO CERCADO','BAIRRO NOVO',66);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11406,'QUITANDINHA 2','R. DOS PIONEIROS',562,'SITIO CERCADO','BAIRRO NOVO',66);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11462,'RIO BARIGUI 1','R. DEP. HEITOR ALENCAR FURTADO',1025,'MOSSUNGUE','SANTA FELICIDADE',46);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11463,'RIO BARIGUI 2','R. DEP. HEITOR ALENCAR FURTADO',1026,'MOSSUNGUE','SANTA FELICIDADE',46);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11359,'ROBERTO HAUER 1','AV. MAL. FLORIANO PEIXOTO',5015,'HAUER','BOQUEIRAO',37);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11358,'ROBERTO HAUER 2','AV. MAL. FLORIANO PEIXOTO',5166,'HAUER','BOQUEIRAO',37);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11437,'RODOFERROVIARIA 1','AV. PRES. AFFONSO CAMARGO',345,'JARDIM BOTANICO','MATRIZ',39);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11436,'RODOFERROVIARIA 2','AV. PRES. AFFONSO CAMARGO',330,'JARDIM BOTANICO','MATRIZ',39);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11403,'ROSA TORTATO 1','R. RICARDO GASPARIAN MACHADO',1139,'PINHEIRINHO','PINHEIRINHO',51);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11402,'ROSA TORTATO 2','R. RICARDO GASPARIAN MACHADO',1140,'PINHEIRINHO','PINHEIRINHO',51);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11401,'SAGRADO CORACAO 1','R. RICARDO GASPARIAN MACHADO',649,'PINHEIRINHO','PINHEIRINHO',51);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11400,'SAGRADO CORACAO 2','R. RICARDO GASPARIAN MACHADO',650,'PINHEIRINHO','PINHEIRINHO',51);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11478,'SANTA BERNADETHE 1','ROD. BR-476',14497,'XAXIM','BOQUEIRAO',75);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11479,'SANTA BERNADETHE 2','ROD. BR-476',14502,'FANNY','PINHEIRINHO',32);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11337,'SANTA REGINA 1','AV. WINSTON CHURCHILL',797,'CAPAO RASO','PINHEIRINHO',25);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11336,'SANTA REGINA 2','AV. WINSTON CHURCHILL',924,'CAPAO RASO','PINHEIRINHO',25);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11466,'SAO GRATO 1','R. DEP. HEITOR ALENCAR FURTADO',2205,'MOSSUNGUE','SANTA FELICIDADE',46);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11467,'SAO GRATO 2','R. DEP. HEITOR ALENCAR FURTADO',2206,'MOSSUNGUE','SANTA FELICIDADE',46);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11474,'SAO PEDRO 1','ROD. BR-476',17511,'XAXIM','BOQUEIRAO',75);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11475,'SAO PEDRO 2','ROD. BR-476',17518,'CAPAO RASO','PINHEIRINHO',25);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11318,'SEBASTIAO PARANA 1','AV. REPUBLICA ARGENTINA',1535,'AGUA VERDE','PORTAO',2);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11319,'SEBASTIAO PARANA 2','AV. REPUBLICA ARGENTINA',1662,'VILA IZABEL','PORTAO',73);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11312,'SILVA JARDIM 1','AV. REPUBLICA ARGENTINA',235,'AGUA VERDE','PORTAO',2);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11313,'SILVA JARDIM 2','AV. REPUBLICA ARGENTINA',230,'AGUA VERDE','PORTAO',2);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11419,'TEOFILO OTONI 1','R. ENG. COSTA BARROS',1265,'CAJURU','CAJURU',20);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11418,'TEOFILO OTONI 2','R. ENG. COSTA BARROS',1266,'CAJURU','CAJURU',20);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11353,'TRE 1','AV. MAL. FLORIANO PEIXOTO',3333,'PRADO VELHO','MATRIZ',53);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11352,'TRE 2','AV. MAL. FLORIANO PEIXOTO',3454,'PAROLIN','PORTAO',49);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11429,'URBANO LOPES 1','AV. PRES. AFFONSO CAMARGO',2539,'CRISTO REI','MATRIZ',31);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11428,'URBANO LOPES 2','AV. PRES. AFFONSO CAMARGO',2540,'JARDIM BOTANICO','MATRIZ',39);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11472,'U.S. CAMPO COMPRIDO 1','R. DEP. HEITOR ALENCAR FURTADO',3641,'CAMPO COMPRIDO','SANTA FELICIDADE',22);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11473,'U.S. CAMPO COMPRIDO 2','R. DEP. HEITOR ALENCAR FURTADO',3710,'CAMPO COMPRIDO','SANTA FELICIDADE',22);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11343,'UTFPR 1','AV. MAL. FLORIANO PEIXOTO',965,'REBOUCAS','MATRIZ',54);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11342,'UTFPR 2','AV. MAL. FLORIANO PEIXOTO',990,'REBOUCAS','MATRIZ',54);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11485,'UTFPR 3','AV. MAL. FLORIANO PEIXOTO',995,'REBOUCAS','MATRIZ',54);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11484,'UTFPR 4','AV. MAL. FLORIANO PEIXOTO',1020,'REBOUCAS','MATRIZ',54);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11435,'VIADUTO DO CAPANEMA 1','AV. PRES. AFFONSO CAMARGO',939,'CRISTO REI','MATRIZ',31);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11434,'VIADUTO DO CAPANEMA 2','AV. PRES. AFFONSO CAMARGO',940,'JARDIM BOTANICO','MATRIZ',39);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11408,'VILA NOVA 1','AV. PRES. AFFONSO CAMARGO',6599,'CAPAO DA IMBUIA','CAJURU',24);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11409,'VILA NOVA 2','AV. PRES. AFFONSO CAMARGO',6600,'CAJURU','CAJURU',20);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (13399,'VILA OLIMPICA 1','ROD. BR-476',5870,'JARDIM SOCIAL','MATRIZ',41);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (13400,'VILA OLIMPICA 2','ROD. BR-476',5870,'BAIRRO ALTO','BOA VISTA',10);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11447,'VISCONDE DE NACAR 1','R. PROF. FERNANDO MOREIRA',50,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11446,'VISCONDE DE NACAR 2','R. PROF. FERNANDO MOREIRA',33,'CENTRO','MATRIZ',28);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11320,'VITAL BRASIL 1','AV. REPUBLICA ARGENTINA',1987,'AGUA VERDE','PORTAO',2);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11321,'VITAL BRASIL 2','AV. REPUBLICA ARGENTINA',2058,'PORTAO','PORTAO',52);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11397,'WENCESLAU BRAZ 1','AV. PRES. WENCESLAU BRAZ',3241,'NOVO MUNDO','PINHEIRINHO',47);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11396,'WENCESLAU BRAZ 2','AV. PRES. WENCESLAU BRAZ',3220,'PORTAO','PORTAO',52);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11399,'WINSTON CHURCHILL 1','AV. WINSTON CHURCHILL',2759,'PINHEIRINHO','PINHEIRINHO',51);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11398,'WINSTON CHURCHILL 2','AV. WINSTON CHURCHILL',2768,'PINHEIRINHO','PINHEIRINHO',51);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11476,'XAXIM 1','ROD. BR-476',16099,'XAXIM','BOQUEIRAO',75);
INSERT INTO g5_ponto_de_onibus_canaleta(id_ponto,nome_ponto,rua,numero,bairro,regional,id_bairro) VALUES (11477,'XAXIM 2','ROD. BR-476',16100,'CAPAO RASO','PINHEIRINHO',25);


